---
title: "R Notebook"
output: html_notebook
---



```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/s1584495/Desktop/R mess/instructions")
```

```{r}
test1 <- 1
test_two <- 2
test.three <- "3"
test1 + test_two
test1+test.three

iris <- iris
names(iris)
head(iris)
summary(iris)
```

```{r}
install.packages("tidyverse")
library(tidyverse)
```
```{r}
iris.filt <- iris %>% 
  filter(Petal.Width > 0.1) %>% 
  select(-Sepal.Length, -Sepal.Width) %>% 
  group_by(Species) %>% 
  summarise(mean.length = mean(Petal.Length))
head(iris.filt)

new.c <- c("alpha", "beta" )
new.col <- sample(new.c, size = 150, replace=TRUE)
iris.plus <- cbind(iris, new.col)

iris.forAnu <- iris.plus %>% 
    group_by(Species, new.col) %>% 
  summarise(mean.length = mean(Petal.Length))
head(iris.forAnu)

  
```
```{r}
ggplot(data=iris.forAnu, aes(x=Species, y=mean.length, fill=new.col)) +
    geom_bar(stat="identity", position=position_dodge())
```

```{r}
iris.forerror <- iris %>% 
  filter(Petal.Width > 0.1) %>% 
  select(-Sepal.Length, -Sepal.Width) %>% 
  group_by(Species) %>% 
  summarise(mean.length = mean(Petal.Length), sd.length = sd(Petal.Length))
head(iris.forerror)

ggplot(data=iris.forerror, aes(x=Species, y=mean.length)) +
    geom_bar(stat="identity") +  
    geom_errorbar(aes(ymin=mean.length-sd.length, ymax=mean.length+sd.length),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))
```
```{r}
iris.wide <- iris %>% 
  mutate(no = 1:n())
  
  
  
iris.setosa <- pivot_wider(iris.wide, names_from = Species, values_from = c(Petal.Length, Petal.Width, Sepal.Length, Sepal.Width)) %>% 
  select(contains("setosa"))

head(iris.setosa)

iris.newwide <- pivot_wider(iris, names_from = Species, values_from = c(Petal.Length, Petal.Width, Sepal.Length, Sepal.Width)) 

iris.newwide


plot1 <- ggplot(data=iris.forerror, aes(x=Species, y=mean.length)) +
    geom_bar(stat="identity") +  
    geom_errorbar(aes(ymin=mean.length-sd.length, ymax=mean.length+sd.length),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))

pdf("myplot.pdf")
plot1
dev.off()

while (!is.null(dev.list()))  dev.off()

write.csv(iris.setosa, "setosa.csv")

```

